spring:
  application:
    name: fazenda_crud_api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Satyan123
    url: jdbc:mysql://localhost:3306/fazenda_satyan?createDatabaseIfNotExist=true
